
package votingsystem.voteanalysis;

import java.sql.SQLException;
import java.text.MessageFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import static votingsystem.databaseconnection.DatabaseConnection.*;
import net.proteanit.sql.DbUtils;


public class Vote_Analysis extends javax.swing.JDialog {

    /**
     * Creates new form Vote_Analysis
     */
    public Vote_Analysis(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
         setIconImage(new ImageIcon("votingsystem.images//maseno.png").getImage());
        setLocationRelativeTo(null);
         tblAnalysis.setVisible(false);
        try {
            new votingsystem.databaseconnection.DatabaseConnection().dbConnect();
        } catch (SQLException ex) {
            Logger.getLogger(Vote_Analysis.class.getName()).log(Level.SEVERE, null, ex);
        }
       
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblAnalysis = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        cmbAnalysis = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        lblAnalysis = new javax.swing.JLabel();
        btnPrint = new javax.swing.JButton();

        jLabel2.setText("jLabel2");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        tblAnalysis.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        tblAnalysis.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblAnalysis.setEnabled(false);
        jScrollPane1.setViewportView(tblAnalysis);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 0, 204));
        jLabel1.setText("Voter Turn Out");

        cmbAnalysis.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        cmbAnalysis.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "----Please Select category---", "TOTAL", "MALE", "FEMALE" }));
        cmbAnalysis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbAnalysisActionPerformed(evt);
            }
        });

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/somu/img/msu_banner2.png"))); // NOI18N

        lblAnalysis.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblAnalysis.setForeground(new java.awt.Color(255, 0, 255));
        lblAnalysis.setText("MASENO UNIVERSITY VOTER TURN OUT ANALYSIS");

        btnPrint.setText("Print");
        btnPrint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrintActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 689, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(106, 106, 106)
                        .addComponent(jLabel1)
                        .addGap(71, 71, 71)
                        .addComponent(cmbAnalysis, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 517, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblAnalysis, javax.swing.GroupLayout.PREFERRED_SIZE, 512, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(303, 303, 303)
                        .addComponent(btnPrint)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(cmbAnalysis, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(lblAnalysis)
                .addGap(12, 12, 12)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnPrint, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmbAnalysisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbAnalysisActionPerformed
        if(0==cmbAnalysis.getSelectedIndex()){
        tblAnalysis.setVisible(false);
        }
        else if (1==cmbAnalysis.getSelectedIndex()){
        try{
             tblAnalysis.setVisible(true);
        String sql ="select(SELECT COUNT(*) FROM register_voter) AS Registered_Voters,(SELECT COUNT(*)FROM register_voter WHERE Status='-1') as Votes_Cast,(SELECT COUNT(*) FROM register_voter WHERE Status='0')as Votes_Not_Cast,(SELECT (votes_Cast/Registered_Voters)*100)as Percentage_Turnout"  ;
         pstmt=con.prepareStatement(sql);
         rs=pstmt.executeQuery();
         tblAnalysis.setModel(DbUtils.resultSetToTableModel(rs));
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
 }
        else if(2==cmbAnalysis.getSelectedIndex()){
            try{
             String sql ="select(SELECT COUNT(*) FROM register_voter WHERE Gender='Male') AS Registered_Male_Voters,(SELECT COUNT(*)FROM register_voter WHERE Status='-1' and Gender='Male') as Votes_Cast,(SELECT COUNT(*) FROM register_voter WHERE Status='0'and Gender='Male')as Votes_Not_Cast,(SELECT (votes_Cast/Registered_Male_Voters)*100)as Percentage_Turnout"  ;
           pstmt=con.prepareStatement(sql);
         rs=pstmt.executeQuery();
         tblAnalysis.setModel(DbUtils.resultSetToTableModel(rs));
            
            }
            
            catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
            }
                
                }
        else if (3==cmbAnalysis.getSelectedIndex()){
        try{
             String sql ="select(SELECT COUNT(*) FROM register_voter WHERE Gender='Female') AS Registered_Female_Voters,(SELECT COUNT(*)FROM register_voter WHERE Status='-1' and Gender='Female') as Votes_Cast,(SELECT COUNT(*) FROM register_voter WHERE Status='0'and Gender='Female')as Votes_Not_Cast,(SELECT (votes_Cast/Registered_Female_Voters)*100)as Percentage_Turnout"  ;
           pstmt=con.prepareStatement(sql);
         rs=pstmt.executeQuery();
         tblAnalysis.setModel(DbUtils.resultSetToTableModel(rs));
            
            }
            
            catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
            }
        
        }
    }//GEN-LAST:event_cmbAnalysisActionPerformed

    private void btnPrintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrintActionPerformed
       String x=(String) cmbAnalysis.getSelectedItem();
        
        MessageFormat header = new MessageFormat("MASINDE MULIRO UNIVERSITY  "+x+"  VOTER TURNOUT ANALYSIS");
        MessageFormat footer = new MessageFormat("Page {0,number,integer}");
        try {
            tblAnalysis.print(JTable.PrintMode.NORMAL, header, footer);

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_btnPrintActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Vote_Analysis.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Vote_Analysis.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Vote_Analysis.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Vote_Analysis.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Vote_Analysis dialog = new Vote_Analysis(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPrint;
    private javax.swing.JComboBox cmbAnalysis;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblAnalysis;
    private javax.swing.JTable tblAnalysis;
    // End of variables declaration//GEN-END:variables
}

